Add a community resource tiddler documenting Projectify
Jermolene/TiddlyWiki5 pull request #5372
Opened 2021-01-06 17:43 UTC by NicolasPetton

This pull requests adds a community resource tiddler explaining what Projectify is and what features it provides.

2021-01-09 13:47 UTC, Jermolene commented
Thanks @NicolasPetton and apologies for the delay. Pure documentation updates should target the "tiddlywiki-com" branch which enables us to push them immediately to tiddlywiki.com without waiting for the usual release cycle.

2021-01-09 14:56 UTC, kookma commented
@NicolasPetton - Please also https://tiddlywiki.com/#%22Notebook%2C%20a%20clean%2C%20uncluttered%20theme%20for%20TiddlyWiki%22%20by%20Nicolas%20Petton and check if the tiddler title and content are consistent and sufficient. I may suggest a shorter tiddler title like Notebook theme or clean them,...
I appreciate to double check.

2021-01-10 12:54 UTC, OdinJorna requested changes

2021-01-10 19:43 UTC, NicolasPetton commented on editions/tw5.com/tiddlers/community/resources/Projectify by Nicolas Petton.tid
> +tags: Resources
Thanks, fixed.

2021-01-10 19:45 UTC, NicolasPetton commented
@Jermolene I updated the base branch, thanks.

2021-01-10 20:12 UTC, NicolasPetton commented
@kookma I'll open a separate pull request to update the tiddler about Notebook.

2021-01-13 10:26 UTC, NicolasPetton commented
@Jermolene ping :smile:

2021-01-13 12:51 UTC, Jermolene commented
Thanks @NicolasPetton

2021-01-13 12:51 UTC, merged