Add indentation to plugin-info, to make the macros readable.
Jermolene/TiddlyWiki5 pull request #5777
Opened 2021-06-10 18:06 UTC by pmario

@Jermolene ... This PR adds indentation to make the code human readable. It also adds 2 non-breakable-spaces that will be removed by `\whitespace trim`

I intend to modify this tiddler, to implement translatable plugins and eventually add the functionality discussed at: "A new type of plugins for distributing contents like course notes, presentations, ordinary bundle of tiddlers" #5462

2021-06-11 16:11 UTC, Jermolene requested changes
Thanks @pmario

2021-06-11 18:20 UTC, pmario commented
@Jermolene ... fixed it.

2021-07-21 13:16 UTC, pmario commented
@Jermolene ... I did add the requested indent. So IMO the PR can be merged now

2021-07-26 16:22 UTC, pmario commented
@Jermolene ... bump ... Please consider this one

2021-07-26 20:58 UTC, Jermolene commented
Thanks @pmario

2021-07-26 20:59 UTC, merged